// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcyaosgoqkchwykmkckw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeWFvc2dvcWtjaHd5a21rY2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzMxODksImV4cCI6MjA2NzQwOTE4OX0.rKKsbycb6-OldPMo88kfl5jDxsgAzhWwMVU3Qe29vf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});